language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    
install: true
    
script:
  - ./mvnw clean install
  # Code Coverage using codecov service (uses JaCoCo)
  - bash <(curl -s https://codecov.io/bash)
