language: java
sudo: false
install: true

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
addons:
  sonarcloud:
    organization: "Francisco Breno"
    token:
      secure: $SONARCUBE_TOKEN
      
script:
  - mvn clean verify sonar:sonar

after_success:
  # Code Coverage using codecov service (uses JaCoCo)
  - bash <(curl -s https://codecov.io/bash)
